In [2]:
import gym
import numpy as np 
import time
import random

from IPython.display import clear_output

In [ ]:
%%debug
# Dubugging tutorial - Press n for next line and c for continue execution. 
for i in range(10):
    print(i)

NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
> <string>(3)<module>()



In [4]:
env = gym.make('FrozenLake-v0')
env.reset()

0

In [8]:
state_space_size = env.observation_space.n
print('state space: ',env.observation_space.n)

state space:  16


In [9]:
action_space_size = env.action_space.n
print('Action space: ',env.action_space.n)

Action space:  4


In [10]:
q_table = np.zeros((state_space_size,action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001


# Update q table using the below formula

New Q value is the weighted sum of the old value and new value. Which is explained below. 

<img src="update_q_table.png"/>

In [15]:
# Construct a Q-Table or Training algorithm. 

rewards_all_episodes = []

#Q-Learning algorithm
for episode in range(num_episodes):
    state = env.reset()  
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        #exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample() # Choose a random action from the environment. 
        
        new_state, reward, done, info = env.step(action) # run the selected action in the env and receive the output.
        
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * (reward + discount_rate * np.max(q_table[new_state,:]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    # Exploration rate decay
    
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all_episodes.append(rewards_current_episode)
    
# Calculate and print the average reward per thousand episodes
rewards_per_thousand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000
print("****Average reward per thousand episodes**********\n")
for r in rewards_per_thousand_episodes:
    print(count,":", str(sum(r/1000)))
    count += 1000

print("******* updated Q_table*****")
print(q_table)

****Average reward per thousand episodes**********

1000 : 0.5290000000000004
2000 : 0.6930000000000005
3000 : 0.7130000000000005
4000 : 0.6580000000000005
5000 : 0.6850000000000005
6000 : 0.6680000000000005
7000 : 0.7080000000000005
8000 : 0.6990000000000005
9000 : 0.7050000000000005
10000 : 0.6980000000000005
******* updated Q_table*****
[[0.53783399 0.52996813 0.52341931 0.5243964 ]
 [0.35239994 0.2091119  0.32447276 0.51954534]
 [0.42599622 0.43152801 0.41120538 0.48359435]
 [0.32833003 0.35702951 0.32061339 0.46052118]
 [0.55254044 0.36110572 0.34926549 0.31971424]
 [0.         0.         0.         0.        ]
 [0.22999188 0.16263761 0.35803403 0.13057157]
 [0.         0.         0.         0.        ]
 [0.44351249 0.44040275 0.48038172 0.57945858]
 [0.56532687 0.64751395 0.48979178 0.45498167]
 [0.65389181 0.37087765 0.35543052 0.36170775]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.54679481 0.50707496 0.71320451 0.48706709]


In [21]:
print(q_table)
time.sleep(3)

for episode in range(3):
    state = env.reset()
    done = False
    print("**** EPISODE ", episode,"****\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])
        new_state, reward, done, info = env.step(action) # Will return the response for the action taken
        # in the environment. 
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("[+] you reached the goal")
                time.sleep(3)
            else:
                print("[+] you fell through the hole!")
                time.sleep(3)
            clear_output(wait=True)
            break
            
        state = new_state
        
env.close()                

  (Down)
SFFF
FHFH
FFFH
HFFG
[+] you reached the goal
